version: '3.8'
services:
  gAuthCraft:
    build: .
    ports:
      - "3000:3000"
    environment:
      - HTTP_PORT=3000
      - JWT_SECRET=your_secret_key
    volumes:
      - .:/usr/src/app/CraftFlow
      - /usr/src/app/CraftFlow/node_modules
