services:
  gauthcraft:
    build:
      context: .
    ports:
      - "3000:3000" # HTTP
      - "50051:50051" # gRPC
    env_file:
      - ./src/config/.env
    depends_on:
      - jenkins
  jenkins:
      image: jenkins/jenkins:lts
      container_name: jenkins
      ports:
        - "8080:8080"
        - "50000:50000"
      volumes:
        - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: